[package]
name = "backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
actix-web = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["full", "rt-multi-thread"] }
reqwest = { workspace = true, features = ["json"] }
chrono = { workspace = true }
actix-cors = { workspace = true }
actix-files = { workspace = true }
common = { workspace = true }
tracing = { workspace = true }
tracing-actix-web = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "macros", "chrono", "migrate"] }
actix-web-httpauth = { workspace = true }
jsonwebtoken = { workspace = true }
bcrypt = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
once_cell = { workspace = true }
figment = { workspace = true, features = ["toml", "env"] }
validator = { workspace = true, features = ["derive"] }
rand = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
actix-governor = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras", "chrono", "openapi_extensions"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }
uuid = { workspace = true, features = ["v4"] }

[features]
default = ["svelte-ui", "db-sqlite"]
svelte-ui = []
slint-ui = []
db-sqlite = ["sqlx/sqlite", "common/db-sqlite"]
db-postgres = ["sqlx/postgres", "common/db-postgres"]

[lib]
name = "backend"
path = "src/lib.rs"

[dev-dependencies]
# Dependencies needed ONLY for running tests and benchmarks

# For deserializing JSON in our tests
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "postgres", "macros"] }
